array : array.c
	gcc -o array array.c

arraylist: arraylist.c
	gcc -o arraylist array.c

linkedlist: linkedlist.c
	gcc -o linkedlist linkedlist.c

matrix : matrix.c 
	gcc -o matrix matrix.c

points : points.c
	gcc -o points points.c